### ISSUE TITLE
app doesnt run on my box

### ISSUE THREAD

**Issue by mogorman** [sagivo/StockStalk#12]
```
[mog@worklaptop:~/StockStalk]$ yarn install
yarn install v1.0.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.12s.

[mog@worklaptop:~/StockStalk]$ yarn dev
yarn dev v1.0.1
$ concurrently "BROWSER=none yarn start" "wait-on http://localhost:3000 && electron ."
[0] watching css
[0] Starting the development server...
[0] 
[1] events.js:160
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: spawn /home/betterlesson/StockStalk/node_modules/electron/dist/electron ENOENT
[1]     at exports._errnoException (util.js:1020:11)
[1]     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
[1]     at onErrorNT (internal/child_process.js:376:16)
[1]     at _combinedTickCallback (internal/process/next_tick.js:80:11)
[1]     at process._tickCallback (internal/process/next_tick.js:104:9)
[1]     at Module.runMain (module.js:606:11)
[1]     at run (bootstrap_node.js:383:7)
[1]     at startup (bootstrap_node.js:149:9)
[1]     at bootstrap_node.js:496:3
[1] wait-on http://localhost:3000 && electron . exited with code 1
[0] Failed to compile.
[0] 
[0] ./src/Login.js
[0] Module not found: Can't resolve './helpers/firebase' in '/home/betterlesson/StockStalk/src'
```

when i just try to go to localhost:3000 directly I get this error
```
Failed to compile
./src/Login.js
Module not found: Can't resolve './helpers/firebase' in '/home/betterlesson/StockStalk/src'
This error occurred during the build time and cannot be dismissed.
```

**Comment by sagivo** [comment]
Seams like related to your firebase settings. 
update here https://github.com/sagivo/StockStalk/commit/c202b53bb797323fe3403322bf4c9f9a9b2a65d0
